Use `isMainRequest` when available
FriendsOfSymfony/FOSRestBundle pull request #2310
Opened 2021-06-07 09:31 UTC by ruudk

Symfony 5.3 deprecates `isMasterRequest` in favor of `isMainRequest`.

2021-06-10 09:29 UTC, xabbuh requested changes

2021-06-10 09:29 UTC, xabbuh commented on EventListener/ResponseStatusCodeListener.php
> +        if (!$event->isMainRequest($event)) {
`$this->isMainRequest($event)`

2021-06-10 09:36 UTC, ruudk commented on EventListener/ResponseStatusCodeListener.php
> +        if (!$event->isMainRequest($event)) {
Ouch. Fixed.

2021-06-10 11:55 UTC, xabbuh approved these changes

2021-07-09 08:16 UTC, xabbuh commented
Thank you @ruudk.

2021-07-09 08:16 UTC, merged